In [1]:
import pandas as pd

In [5]:
pd.DataFrame(data={'3':[4,5],'5':[6,2],'7':[8,19]})

3  5   7
0  4  6   8
1  5  2  19

In [6]:
postseasonteams_a0=['TBR','MIN','OAK','NYY','CLE','LAD','CIN','ATL','STL','SD'] #these are the would-be postseason teams in a "normal" 2020 season

In [7]:
import numpy

In [8]:
numpy.array([[0]*10]*10)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [9]:
n=_

In [10]:
n

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [11]:
postseasonteams_a0

['TBR', 'MIN', 'OAK', 'NYY', 'CLE', 'LAD', 'CIN', 'ATL', 'STL', 'SD']

In [14]:
n[0][1]=2/7

In [15]:
n

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [16]:
n

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [22]:
n[0,1]=0.2857

In [24]:
n[n==0]=16

In [21]:
2/7

0.2857142857142857

In [26]:
n[n==16]=0

In [27]:
n

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [28]:
n[0,1]

0

In [29]:
n[0,1]=27

In [30]:
n

array([[ 0, 27,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [33]:
n[0,1]=2 #In the last series the Twins beat the Rays 5 times out of 7. This means the Rays beat the Twins 2 times out of 7.

In [34]:
n[1,0]=5

In [35]:
n

array([[0, 2, 0, 0, 0, 0, 0, 0, 0, 0],
       [5, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [36]:
p=postseasonteams_a0

In [37]:
p

['TBR', 'MIN', 'OAK', 'NYY', 'CLE', 'LAD', 'CIN', 'ATL', 'STL', 'SD']

In [38]:
n[0,2]=3;n[2,0]=4

In [39]:
n[0,3]=3;n[3,0]=2

In [40]:
n[0,4]=6;n[4,0]=1

In [41]:
n[0,5]=2;n[5,0]=4

In [42]:
n[0,6]=2;n[6,0]=1

In [44]:
n[0,8]=2;n[8,0]=1

In [45]:
n[0,7]=2;n[7,0]=1

In [46]:
n[0,9]=2;n[9,0]=1

In [47]:
n

array([[0, 2, 3, 3, 6, 2, 2, 2, 2, 2],
       [5, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [4, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [2, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [4, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [48]:
p

['TBR', 'MIN', 'OAK', 'NYY', 'CLE', 'LAD', 'CIN', 'ATL', 'STL', 'SD']

In [49]:
n[1,4] = 7;n[4,1] = 3

In [50]:
n[1,6] = 1;n[6,1] = 2

In [51]:
n[1,8]=3;n[8,1]=1

In [52]:
n[1,2]=3;n[2,1]=4

In [53]:
n[1,3]=2;n[3,1]=4

In [54]:
n[1,7]=1;n[7,1]=2

In [55]:
n[1,5]=0;n[5,1]=3

In [56]:
n[1,9]=3;n[9,1]=1

In [57]:
n

array([[0, 2, 3, 3, 6, 2, 2, 2, 2, 2],
       [5, 0, 3, 2, 7, 0, 1, 1, 3, 3],
       [4, 4, 0, 0, 0, 0, 0, 0, 0, 0],
       [2, 4, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 3, 0, 0, 0, 0, 0, 0, 0, 0],
       [4, 3, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 2, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 2, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0]])

In [58]:
p

['TBR', 'MIN', 'OAK', 'NYY', 'CLE', 'LAD', 'CIN', 'ATL', 'STL', 'SD']

In [59]:
n[2,5]=1;n[5,2]=2

In [60]:
n[2,9]=1;n[9,2]=2

In [62]:
n[2,3]=4;n[3,2]=2

In [63]:
n[2,4]=5;n[4,2]=1

In [64]:
n[2,6]=2;n[6,2]=1

In [65]:
n[2,8]=4;n[8,2]=0

In [66]:
n[2,7]=0;n[7,2]=3

In [67]:
n

array([[0, 2, 3, 3, 6, 2, 2, 2, 2, 2],
       [5, 0, 3, 2, 7, 0, 1, 1, 3, 3],
       [4, 4, 0, 4, 5, 1, 2, 0, 4, 1],
       [2, 4, 2, 0, 0, 0, 0, 0, 0, 0],
       [1, 3, 1, 0, 0, 0, 0, 0, 0, 0],
       [4, 3, 2, 0, 0, 0, 0, 0, 0, 0],
       [1, 2, 1, 0, 0, 0, 0, 0, 0, 0],
       [1, 2, 3, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 2, 0, 0, 0, 0, 0, 0, 0]])

In [68]:
p

['TBR', 'MIN', 'OAK', 'NYY', 'CLE', 'LAD', 'CIN', 'ATL', 'STL', 'SD']

In [69]:
n[3,4]=2;n[4,3]=0

In [70]:
n[3,7]=2;n[7,3]=2

In [71]:
n[3,5]=2;n[5,3]=1

In [72]:
n[3,9]=2;n[9,3]=1

In [73]:
n[3,6]=3;n[6,3]=1

In [74]:
n[3,8]=3;n[8,3]=0

In [75]:
n

array([[0, 2, 3, 3, 6, 2, 2, 2, 2, 2],
       [5, 0, 3, 2, 7, 0, 1, 1, 3, 3],
       [4, 4, 0, 4, 5, 1, 2, 0, 4, 1],
       [2, 4, 2, 0, 2, 2, 3, 2, 3, 2],
       [1, 3, 1, 0, 0, 0, 0, 0, 0, 0],
       [4, 3, 2, 1, 0, 0, 0, 0, 0, 0],
       [1, 2, 1, 1, 0, 0, 0, 0, 0, 0],
       [1, 2, 3, 2, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 2, 1, 0, 0, 0, 0, 0, 0]])

In [76]:
p

['TBR', 'MIN', 'OAK', 'NYY', 'CLE', 'LAD', 'CIN', 'ATL', 'STL', 'SD']

In [77]:
n[4,6]=3;n[6,4]=1

In [78]:
n[4,8]=2;n[8,4]=1

In [79]:
n[4,7]=1;n[7,4]=2

In [80]:
n[4,5]=1;n[5,4]=2

In [81]:
n[4,9]=1;n[9,4]=2

In [82]:
n

array([[0, 2, 3, 3, 6, 2, 2, 2, 2, 2],
       [5, 0, 3, 2, 7, 0, 1, 1, 3, 3],
       [4, 4, 0, 4, 5, 1, 2, 0, 4, 1],
       [2, 4, 2, 0, 2, 2, 3, 2, 3, 2],
       [1, 3, 1, 0, 0, 1, 3, 1, 2, 1],
       [4, 3, 2, 1, 2, 0, 0, 0, 0, 0],
       [1, 2, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 2, 3, 2, 2, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 1, 0, 0, 0, 0, 0],
       [1, 1, 2, 1, 2, 0, 0, 0, 0, 0]])

In [83]:
p

['TBR', 'MIN', 'OAK', 'NYY', 'CLE', 'LAD', 'CIN', 'ATL', 'STL', 'SD']

In [84]:
n[5,9]=3;n[9,5]=0

In [85]:
n[5,7]=4;n[7,5]=3

In [86]:
n[5,6]=5;n[6,5]=1

In [87]:
n[5,8]=3;n[8,5]=4

In [88]:
n

array([[0, 2, 3, 3, 6, 2, 2, 2, 2, 2],
       [5, 0, 3, 2, 7, 0, 1, 1, 3, 3],
       [4, 4, 0, 4, 5, 1, 2, 0, 4, 1],
       [2, 4, 2, 0, 2, 2, 3, 2, 3, 2],
       [1, 3, 1, 0, 0, 1, 3, 1, 2, 1],
       [4, 3, 2, 1, 2, 0, 5, 4, 3, 3],
       [1, 2, 1, 1, 1, 1, 0, 0, 0, 0],
       [1, 2, 3, 2, 2, 3, 0, 0, 0, 0],
       [1, 1, 0, 0, 1, 4, 0, 0, 0, 0],
       [1, 1, 2, 1, 2, 0, 0, 0, 0, 0]])

In [89]:
p

['TBR', 'MIN', 'OAK', 'NYY', 'CLE', 'LAD', 'CIN', 'ATL', 'STL', 'SD']

In [90]:
n[6,7]=0;n[7,6]=2

In [91]:
n[6,8]=4;n[8,6]=8

In [92]:
n[6,9]=5;n[9,6]=2

In [93]:
n

array([[0, 2, 3, 3, 6, 2, 2, 2, 2, 2],
       [5, 0, 3, 2, 7, 0, 1, 1, 3, 3],
       [4, 4, 0, 4, 5, 1, 2, 0, 4, 1],
       [2, 4, 2, 0, 2, 2, 3, 2, 3, 2],
       [1, 3, 1, 0, 0, 1, 3, 1, 2, 1],
       [4, 3, 2, 1, 2, 0, 5, 4, 3, 3],
       [1, 2, 1, 1, 1, 1, 0, 0, 4, 5],
       [1, 2, 3, 2, 2, 3, 2, 0, 0, 0],
       [1, 1, 0, 0, 1, 4, 8, 0, 0, 0],
       [1, 1, 2, 1, 2, 0, 2, 0, 0, 0]])

In [94]:
n[7,8]=4;n[8,7]=2

In [95]:
n[7,9]=5;n[9,7]=2

In [96]:
n

array([[0, 2, 3, 3, 6, 2, 2, 2, 2, 2],
       [5, 0, 3, 2, 7, 0, 1, 1, 3, 3],
       [4, 4, 0, 4, 5, 1, 2, 0, 4, 1],
       [2, 4, 2, 0, 2, 2, 3, 2, 3, 2],
       [1, 3, 1, 0, 0, 1, 3, 1, 2, 1],
       [4, 3, 2, 1, 2, 0, 5, 4, 3, 3],
       [1, 2, 1, 1, 1, 1, 0, 0, 4, 5],
       [1, 2, 3, 2, 2, 3, 2, 0, 4, 5],
       [1, 1, 0, 0, 1, 4, 8, 2, 0, 0],
       [1, 1, 2, 1, 2, 0, 2, 2, 0, 0]])

In [97]:
n[8,9]=1;n[9,8]=2

In [98]:
n

array([[0, 2, 3, 3, 6, 2, 2, 2, 2, 2],
       [5, 0, 3, 2, 7, 0, 1, 1, 3, 3],
       [4, 4, 0, 4, 5, 1, 2, 0, 4, 1],
       [2, 4, 2, 0, 2, 2, 3, 2, 3, 2],
       [1, 3, 1, 0, 0, 1, 3, 1, 2, 1],
       [4, 3, 2, 1, 2, 0, 5, 4, 3, 3],
       [1, 2, 1, 1, 1, 1, 0, 0, 4, 5],
       [1, 2, 3, 2, 2, 3, 2, 0, 4, 5],
       [1, 1, 0, 0, 1, 4, 8, 2, 0, 1],
       [1, 1, 2, 1, 2, 0, 2, 2, 2, 0]])

In [109]:
def estimated_winner(a,b,m):
    p=0
    e=0
    q = n[a,b]/(n[a,b]+n[b,a])
    if m==3:
        p=p+q**2
        p=p+q**2*(1-q)*2
        e = (1-q)**2*0+2*q*(1-q)**2*1+p*2
        f = q**2*0+2*(1-q)*q**2*1+(1-p)*2
    elif m==5:
        p = p+q**3
        p = p+q**3*(1-q)*3
        p = p+q**3*(1-q)**2*6
        e= (1-q)**3*0+3*q*(1-q)**3*1+6*q**2*(1-q)**3*2+p*3
        f = q**3*0+3*(1-q)*q**3*1+6*(1-q)**2*q**3*2+(1-p)*3
    elif m==7:
        p=p+q**4
        p=p+q**4*(1-q)*4
        p=p+q**4*(1-q)**2*10
        p=p+q**4*(1-q)**3*20
        e = (1-q)**4 + 4 * q * (1-q)**4 * 1 + 10 * q**2 * (1-q)**4 * 2 + 20 * q**3 * (1-q)**4 * 3 + p * 4
        f = q**4     + 4 *(1-q)*   q**4 * 1 + 10 *(1-q)**2*   q**4 * 2 + 20 * (1-q)**3 * q**4 * 3 + (1-p)*4
    return [p,e,f] #this identifies the probability the first team wins, and the expected number of games they win and lose in an m-game series.

In [102]:
estimated_winner(0,1,5) #we will use this to find the expected world series in 2020

[0.144701612423395, 1.1034687927649194, 2.7586719819122987]

In [104]:
estimated_winner(1,0,5)

[0.8552983875766049, 2.7586719819122982, 1.1034687927649196]

In [105]:
p

['TBR', 'MIN', 'OAK', 'NYY', 'CLE', 'LAD', 'CIN', 'ATL', 'STL', 'SD']

In [106]:
estimated_winner(0,3,5)

[0.68256, 2.4393599999999998, 1.6262400000000001]

In [107]:
#this means there is a 0.68256 chance the Rays beat the Yankees, average 2.43936 wins and 1.62624 losses

In [110]:
estimated_winner(3,4,3)

[1.0, 2.0, 0.0]

In [116]:
alds_min = estimated_winner(1,2,5)[0]

In [112]:
#0.36788242993990594 chance the Twins beat the A's.

In [113]:
estimated_winner(0,1,7)

[0.10827364205633462, 1.7801705557572585, 3.8063197671524134]

In [114]:
estimated_winner(0,2,7)

[0.34689991900847916, 2.572256700621582, 3.3212485565416743]

In [117]:
e_rayswin_prbws = alds_min*estimated_winner(0,1,7)[0]+(1-alds_min)*estimated_winner(0,2,7)[0]

In [118]:
e_rayswin_prbws

0.25911350439581127

In [119]:
e_rayswin_e = alds_min*estimated_winner(0,1,7)[1]+(1-alds_min)*estimated_winner(0,2,7)[1]

In [120]:
e_rayswin_f = alds_min*estimated_winner(0,1,7)[2]+(1-alds_min)*estimated_winner(0,2,7)[2]

In [121]:
[0.68256*e_rayswin_prbws,e_rayswin_e,e_rayswin_f] #this covers the ALCS. The first number is their chance of winning the pennant.

[0.17686051356040491, 2.2808621249271623, 3.4996977321950453]

In [122]:
estimated_winner(0,3,5)

[0.68256, 2.4393599999999998, 1.6262400000000001]

In [123]:
estwins  = 2.43936 + 0.6825 * e_rayswin_e

In [124]:
estlosses=1.62624+0.6825*e_rayswin_f

In [149]:
gosh=[0.68256*e_rayswin_prbws,estwins,estlosses] #same as [121] but includes ALDS and ALCS.

In [126]:
p

['TBR', 'MIN', 'OAK', 'NYY', 'CLE', 'LAD', 'CIN', 'ATL', 'STL', 'SD']

In [127]:
estimated_winner(8,9,3)

[0.2592592592592593, 0.8148148148148149, 1.6296296296296295]

In [128]:
#0.3333333333333333333333333333333333333 chance that STL triumphs over SD

In [129]:
estimated_winner(5,8,5)

[0.36788242993990594, 1.7548045457249952, 2.3397393942999942]

In [130]:
estimated_winner(5,9,5)

[1.0, 3.0, 0.0]

In [131]:
0.333333333333333*(1-0.36788242993990594)

0.2107058566866978

In [132]:
#No chance padres beat the dodgers. 0.2107058566866978 chance the Cardinals in NLCS, otherwise Dodgers.

In [133]:
estimated_winner(6,7,5)

[0.0, 0.0, 3.0]

In [135]:
#against the braves...

In [136]:
p

['TBR', 'MIN', 'OAK', 'NYY', 'CLE', 'LAD', 'CIN', 'ATL', 'STL', 'SD']

In [137]:
estimated_winner(5,7,7)

[0.6531000809915207, 3.321248556541674, 2.5722567006215824]

In [152]:
ladnl=estimated_winner(5,7,7)[0]*(1-0.2107058566866978)

In [141]:
#There is a 0.5154880689240506 chance the Dodgers win the NL pennant

In [153]:
stlnl=estimated_winner(8,7,7)[0]*0.333333333333333*(1-0.36788242993990594)

In [145]:
#There is a minuscule 0.0365 chance that the Cardinals win the NL pennant

In [154]:
atlnl=1-0.5154880689240506-0.036514640916441916

In [148]:
#There is a 0.4479972901595076 chance the Braves win the NL pennant

In [150]:
gosh

[0.17686051356040491, 3.9960484002627883, 4.014783702223118]

In [151]:
#these are the TBR statistics up to but not including the WS

In [155]:
p

['TBR', 'MIN', 'OAK', 'NYY', 'CLE', 'LAD', 'CIN', 'ATL', 'STL', 'SD']

In [156]:
estimated_winner(0,5,7) #fate against the dodgers

[0.17329675354366714, 2.0320073159579337, 3.6812985825331506]

In [157]:
estimated_winner(0,7,7) #fate against the braves

[0.8267032464563328, 3.68129858253315, 2.0320073159579337]

In [158]:
estimated_winner(0,8,7) #fate against the cardinals

[0.8267032464563328, 3.68129858253315, 2.0320073159579337]

In [159]:
s0 = ladnl*estimated_winner(0,5,7)[0]+(1-ladnl)*estimated_winner(0,7,7)[0]

In [160]:
s0

0.4898799952023464

In [161]:
s1 = ladnl*estimated_winner(0,5,7)[1]+(1-ladnl)*estimated_winner(0,7,7)[1]

In [162]:
s2 = ladnl*estimated_winner(0,5,7)[2]+(1-ladnl)*estimated_winner(0,7,7)[2]

In [163]:
[s0,s1,s2]

[0.4898799952023464, 2.83110861243299, 2.8821972860580938]

In [164]:
gosh

[0.17686051356040491, 3.9960484002627883, 4.014783702223118]

In [166]:
gosh[0]*s0

0.08664042753445568

In [167]:
#There is a 8.66% chance the Rays win the world series, and a 17.69% chance they make it to begin with.

In [168]:
gosh[1]+gosh[0]*s1

4.496759723402972

In [169]:
#They expect to play 4.4968 wins

In [170]:
gosh[2]+gosh[0]*s2

4.524530594417758

In [ ]:
#and 4.5245 losses